batch_size: 32
hidden_channels: 64
lr: 0.0001
num_classes: 2
num_layers: 4
num_node_features: 149
ratio: 0.8
s_data: .\data_diff
s_date: .\data\[UNC]ADNI-network\dataTS.csv
s_node: .\data\DT_File_MAP.xlsx
s_sparsified: .\sparsification\data\
weight_decay: 1.0e-05
